spring:
  application:
    name: piumteo

  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: info

jwt:
  token:
    expiration:
      access: 3600000

auth:
  cookie:
    secure: false
    same-site: Lax

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
